-- MySQL Script generated by MySQL Workbench
-- Sat Mar 19 12:39:10 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NOT NULL,
  `is_owner` TINYINT(1) NOT NULL DEFAULT 0,
  `is_eater` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_owner_user1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `idRestaurant` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phoneNo` INT NULL,
  `street` VARCHAR(45) NOT NULL,
  `suburb` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `owner_user_idUser` INT NOT NULL,
  PRIMARY KEY (`idRestaurant`),
  INDEX `fk_restaurant_owner1_idx` (`owner_user_idUser` ASC),
  CONSTRAINT `fk_restaurant_owner1`
    FOREIGN KEY (`owner_user_idUser`)
    REFERENCES `mydb`.`Owner` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eater`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eater` (
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Eater_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GroupChat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GroupChat` (
  `idGroupChat` INT NOT NULL AUTO_INCREMENT,
  `restaurant_idRestaurant` INT NOT NULL,
  PRIMARY KEY (`idGroupChat`),
  INDEX `fk_GroupChat_restaurant1_idx` (`restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_GroupChat_restaurant1`
    FOREIGN KEY (`restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `GroupChat_idGroupChat` INT NOT NULL,
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(300) NOT NULL,
  `time_sent` INT NULL,
  `idSender` INT NOT NULL,
  INDEX `fk_Message_GroupChat1_idx` (`GroupChat_idGroupChat` ASC),
  PRIMARY KEY (`idMessage`),
  INDEX `fk_Message_User1_idx` (`idSender` ASC),
  CONSTRAINT `fk_Message_GroupChat1`
    FOREIGN KEY (`GroupChat_idGroupChat`)
    REFERENCES `mydb`.`GroupChat` (`idGroupChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`idSender`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EaterRestaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EaterRestaurant` (
  `idEaterRestaurant` INT NOT NULL AUTO_INCREMENT,
  `Eater_user_idUser` INT NOT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  `been_to` TINYINT(1) NOT NULL DEFAULT 0,
  `going_considering` ENUM('G', 'C', 'N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`idEaterRestaurant`),
  INDEX `fk_EaterRestaurant_Eater1_idx` (`Eater_user_idUser` ASC),
  INDEX `fk_EaterRestaurant_Restaurant1_idx` (`Restaurant_idRestaurant` ASC),
  CONSTRAINT `fk_EaterRestaurant_Eater1`
    FOREIGN KEY (`Eater_user_idUser`)
    REFERENCES `mydb`.`Eater` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EaterRestaurant_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserGroupChat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserGroupChat` (
  `idUserGroupChat` INT NOT NULL AUTO_INCREMENT,
  `GroupChat_idGroupChat` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idUserGroupChat`),
  INDEX `fk_UserGroupChat_GroupChat1_idx` (`GroupChat_idGroupChat` ASC),
  INDEX `fk_UserGroupChat_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_UserGroupChat_GroupChat1`
    FOREIGN KEY (`GroupChat_idGroupChat`)
    REFERENCES `mydb`.`GroupChat` (`idGroupChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserGroupChat_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserMessage` (
  `idUserMessage` INT NOT NULL AUTO_INCREMENT,
  `Message_idMessage` INT NOT NULL,
  `UserGroupChat_idUserGroupChat` INT NOT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUserMessage`),
  INDEX `fk_UserMessage_Message1_idx` (`Message_idMessage` ASC),
  INDEX `fk_UserMessage_UserGroupChat1_idx` (`UserGroupChat_idUserGroupChat` ASC),
  CONSTRAINT `fk_UserMessage_Message1`
    FOREIGN KEY (`Message_idMessage`)
    REFERENCES `mydb`.`Message` (`idMessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserMessage_UserGroupChat1`
    FOREIGN KEY (`UserGroupChat_idUserGroupChat`)
    REFERENCES `mydb`.`UserGroupChat` (`idUserGroupChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`User` (`idUser`, `alias`, `is_owner`, `is_eater`) VALUES (1, 'test', true, false);
INSERT INTO `mydb`.`User` (`idUser`, `alias`, `is_owner`, `is_eater`) VALUES (2, 'test1', false, true);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Owner`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Owner` (`User_idUser`) VALUES (1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Restaurant`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Restaurant` (`idRestaurant`, `name`, `phoneNo`, `street`, `suburb`, `city`, `owner_user_idUser`) VALUES (1, 'testtest', 123456, '01 test street', 'test', 'melb', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Eater`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Eater` (`User_idUser`) VALUES (2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`GroupChat`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`GroupChat` (`idGroupChat`, `restaurant_idRestaurant`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Message`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Message` (`GroupChat_idGroupChat`, `idMessage`, `content`, `time_sent`, `idSender`) VALUES (1, 1, 'Welcome', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`EaterRestaurant`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`EaterRestaurant` (`idEaterRestaurant`, `Eater_user_idUser`, `Restaurant_idRestaurant`, `been_to`, `going_considering`) VALUES (1, 2, 1, false, 'G');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`UserGroupChat`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`UserGroupChat` (`idUserGroupChat`, `GroupChat_idGroupChat`, `User_idUser`) VALUES (1, 1, 1);
INSERT INTO `mydb`.`UserGroupChat` (`idUserGroupChat`, `GroupChat_idGroupChat`, `User_idUser`) VALUES (2, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`UserMessage`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`UserMessage` (`idUserMessage`, `Message_idMessage`, `UserGroupChat_idUserGroupChat`, `read`) VALUES (1, 1, 1, true);

COMMIT;

